---
title: "Translation Direction ANOVA"
author: "Isaac Falconer"
date: "2/16/2021"
output:
  word_document: default
  pdf_document: default
---

```{r echo=FALSE, include=FALSE}
# Load required packages
#library(stats)
#library(factoextra)
#library(clusterSim)
#library(tibble)
#library(analogue)
library(gplots)
library(lme4)
library(nlme)
library(lmerTest)
library(MuMIn)
library(tidyverse)
library(readxl)
library(knitr)
library(cAIC4)
library(MASS)
library(glmmLasso)
library(performance)
library(moments)
library(devtools)
library(ggpubr)
library(rstatix)
```

```{r echo=FALSE}

setwd("R:/KiranLab4/Students/Isaac Falconer/ProCoM/BAT-C - LUQ Analysis/Analyses including older data/Mixed Effects Models")
all_data <- read_excel('all_data_mixed_effects_model_weighted_composite_pre_post.xlsx')

skewness(all_data$L1_Background_RC1)
skewness(all_data$L1_Use_RC2)
skewness(all_data$L1_Environment_RC3)
skewness(all_data$L2_Background_Environment_RC1)
skewness(all_data$L2_Use_RC2)
skewness(all_data$WAB_AQ_english)

all_data$sq_L1_Background_RC1 <- (all_data$L1_Background_RC1 + 3)^2
skewness(all_data$sq_L1_Background_RC1)

all_data$L1_Background_RC1 <- scale(all_data$L1_Background_RC1)
all_data$L1_Use_RC2 <- scale(all_data$L1_Use_RC2)
all_data$L1_Environment_RC3 <- scale(all_data$L1_Environment_RC3)
all_data$L2_Background_Environment_RC1 <- scale(all_data$L2_Background_Environment_RC1)
all_data$L2_Use_RC2 <- scale(all_data$L2_Use_RC2)
all_data$WAB_AQ_english <- scale(all_data$WAB_AQ_english)
```

```{r}
all_data$time <- factor(all_data$time, c("pre", "post"), ordered = TRUE)
ggboxplot(all_data, x = "time", y = "composite", add = "jitter")

all_data$direction[1:46] <- "backward"
all_data$direction[47:92] <- "forward"
all_data$direction <- as.factor(all_data$direction)
ggboxplot(all_data, x = "direction", y = "composite", add = "jitter")

```

```{r}

time_dir.aov <- anova_test(composite ~ time * direction, within=c(time, direction), data = all_data)
get_anova_table(time_dir.aov)

```

```{r}

backward_data <- all_data[1:46,]
forward_data <- all_data[47:92,]

t.test(backward_data$composite,forward_data$composite, paired=TRUE)
t.test(all_data$composite[which(all_data$time=="pre")],all_data$composite[which(all_data$time=="post")], paired=TRUE)
```