library(psych)
library(GPArotation)
library(xlsx)
library(MASS)
library(QuantPsyc)
library(gvlma)
library(car)
library(lm.beta)
rm(list = ls())

S3PCA=read.xlsx(file.choose(),1,header = T)
vars.pca<-princomp(~S3PCA$SC+S3PCA$ST+S3PCA$DM+S3PCA$M+S3PCA$DG+S3PCA$GCTI+S3PCA$GCTFM+S3PCA$DSF+S3PCA$DPT+S3PCA$RCPM+S3PCA$CMS+S3PCA$Block+S3PCA$PAPT..,cor=TRUE)
summary(vars.pca)
plot(vars.pca)

fact.vars<-data.frame(S3PCA$SC,S3PCA$ST,S3PCA$DM,S3PCA$M,S3PCA$DG,S3PCA$GCTI,S3PCA$GCTFM,S3PCA$DSF,S3PCA$DPT,S3PCA$RCPM,S3PCA$CMS,S3PCA$Block,S3PCA$PAPT..)
principal(fact.vars,nfactor=4,rotate="varimax")
factorloadings<-principal(fact.vars,nfactor=4,rotate="varimax")

cogprincipal<-principal(fact.vars,nfactor=4,rotate="varimax")
scores<-cogprincipal$scores

write.csv(scores, "scores.csv")
getwd()
Reg=read.xlsx(file.choose(),1,header=TRUE)
Cog<-lm(Reg$PMG~Reg$F1+Reg$F2+Reg$F3+Reg$F4, data=Reg)
summary(Cog)
lm.beta(Cog)
step.Cog<-step(Cog)
summary(step.Cog)
lm.beta(step.Cog)

Reg2=read.xlsx(file.choose(),1,header=TRUE)
Cog2<-lm(Reg2$PMGM~Reg2$F1+Reg2$F2+Reg2$F3+Reg2$F4, data=Reg2)
summary(Cog2)
step.Cog2<-step(Cog2)
summary(step.Cog2)
lm.beta(Cog2)
lm.beta(step.Cog2)

##covariates
#PMG
Reg3=read.xlsx(file.choose(),2,header=TRUE)
cor.test(Reg3$F4, Reg3$LQ)
cor.test(Reg3$F4, Reg3$AOS.DDK)
cor.test(Reg3$F4, Reg3$BNT)

CogLQ<-lm(Reg3$PMG~Reg3$F1+Reg3$F2+Reg3$F3+Reg3$F4+Reg3$LQ, data=Reg3)
summary(CogLQ)
lm.beta(CogLQ)
step.CogLQ<-step(CogLQ)
summary(step.CogLQ)
lm.beta(step.CogLQ)
gvlma(step.CogLQ)

CogAOS<-lm(Reg3$PMG~Reg3$F1+Reg3$F2+Reg3$F3+Reg3$F4+Reg3$AOS.DDK, data=Reg3)
summary(CogAOS)
lm.beta(CogAOS)
step.CogAOS<-step(CogAOS)
summary(step.CogAOS)
lm.beta(step.CogAOS)
gvlma(step.CogAOS)
Reg3=read.xlsx(file.choose(),2,header=TRUE)
CogBNT<-lm(Reg3$PMG~Reg3$F1+Reg3$F2+Reg3$F3+Reg3$F4+Reg3$BNT, data=Reg3 )
summary(CogBNT)
lm.beta(CogBNT)
step.CogBNT<-step(CogBNT)
summary(step.CogBNT)
lm.beta(step.CogBNT)
gvlma(step.CogBNT)

Cogall<-lm(Reg3$PMG~Reg3$F1+Reg3$F2+Reg3$F3+Reg3$F4+Reg3$LQ+Reg3$AOS.DDK+Reg3$BNT, data=Reg3)
summary(Cogall)
lm.beta(Cogall)
step.Cogall<-step(Cogall)
summary(step.Cogall)
lm.beta(step.Cogall)
gvlma(step.Cogall) 

#PMGM
Reg4=read.xlsx(file.choose(),2,header=TRUE)
CogLQ4<-lm(Reg4$PMGM~Reg4$F1+Reg4$F2+Reg4$F3+Reg4$F4,Reg4$LQ, data=Reg4)
summary(CogLQ4)
lm.beta(CogLQ)
step.Cog<-step(CogLQ)
summary(step.CogLQ)
lm.beta(step.CogLQ)

Reg4=read.xlsx(file.choose(),2,header=TRUE)
CogAOS<-lm(Reg$PMGM~Reg4$F1+Reg4$F2+Reg4$F3+Reg4$F4,Reg4$AOS.DDK, data=Reg4)
summary(CogAOS)
lm.beta(CogAOS)
step.Cog<-step(CogAOS)
summary(step.CogAOS)
lm.beta(step.CogAOS)

Reg4=read.xlsx(file.choose(),2,header=TRUE)
CogBNT<-lm(Reg$PMGM~Reg4$F1+Reg4$F2+Reg4$F3+Reg4$F4,Reg4$AOS.DDK, data=Reg4)
summary(CogBNT)
lm.beta(CogBNT)
step.Cog<-step(CogBNT)
summary(step.CogBNT)
lm.beta(step.CogBNT)

###checking model with PMG
outlierTest(Step.Cog)
qqPlot(Step.Cog, main="PMG outliers")
leveragePlots(Step.Cog)
avPlots(Step.Cog)
cutoff<-4/((nrow(Step.Cog)-length(Step.Cog$coefficients)-2))
plot(Step.Cog, which=4, cook.levels=cutoff)
influencePlot(Step.Cog, id.methods="identify", main="Influence Plot", sub="Circle size is proportional to Cook's Distance")
qqPlot(Step.Cog, main="QQ Plot")

sresid<-studres(Step.Cog)
hist(sresid, freq=FALSE, main="Distribution of Studentized Residuals")
xfit<-seq(min(sresid), max(sresid), length=40)
yfit<-dnorm(xfit)
lines(xfit, yfit)
ncvTest(Step.Cog)
spreadLevelPlot(Step.Cog)
vif(Step.Cog)
sqrt(vif(Step.Cog))
crPlots(Step.Cog)
residuals<-residuals(Step.Cog)
mean(Step.Cog$residuals)
acf(Step.Cog$residuals)
durbinWatsonTest(Step.Cog)
gvmodel<-gvlma(Step.Cog)
summary(gvmodel)

par(mfrow=c(2,2))
plot(Step.Cog)


###checking model with PMGM
outlierTest(Step.Cog2)
qqPlot(Step.Cog2, main="PMG outliers")
leveragePlots(Step.Cog2)
avPlots(Step.Cog2)
cutoff<-4/((nrow(Step.Cog2)-length(Step.Cog2$coefficients)-2))
plot(Step.Cog2, which=4, cook.levels=cutoff)
influencePlot(Step.Cog2, id.methods="identify", main="Influence Plot", sub="Circle size is proportional to Cook's Distance")
qqPlot(Step.Cog2, main="QQ Plot")

sresid<-studres(Step.Cog2)
hist(sresid, freq=FALSE, main="Distribution of Studentized Residuals")
xfit<-seq(min(sresid), max(sresid), length=40)
yfit<-dnorm(xfit)
lines(xfit, yfit)
ncvTest(Step.Cog2)
spreadLevelPlot(Step.Cog2)
vif(Step.Cog2)
sqrt(vif(Step.Cog2))
crPlots(Step.Cog2)
residuals<-residuals(Step.Cog2)
mean(Step.Cog2$residuals)
acf(Step.Cog2$residuals)
durbinWatsonTest(Step.Cog2)
gvmodel<-gvlma(Step.Cog2)
summary(gvmodel)

par(mfrow=c(2,2))
plot(Step.Cog2)


outlierTest(Cogall)
qqPlot(Cogall, main="PMG outliers")
leveragePlots(Cogall)
avPlots(Cogall)
cutoff<-4/((nrow(Cogall)-length(Cogall$coefficients)-2))
plot(Cogall, which=4, cook.levels=cutoff)
influencePlot(Cogall, id.methods="identify", main="Influence Plot", sub="Circle size is proportional to Cook's Distance")
qqPlot(Cogall, main="QQ Plot")

sresid<-studres(Cogall)
hist(sresid, freq=FALSE, main="Distribution of Studentized Residuals")
xfit<-seq(min(sresid), max(sresid), length=40)
yfit<-dnorm(xfit)
lines(xfit, yfit)
ncvTest(Cogall)
spreadLevelPlot(Cogall)
vif(Cogall)
sqrt(vif(Cogall))
crPlots(Cogall)
residuals<-residuals(Cogall)
mean(Cogall$residuals)
acf(Cogall$residuals)
durbinWatsonTest(Cogall)
gvmodel<-gvlma(Cogall)
summary(gvmodel)

par(mfrow=c(2,2))
plot(Cogall)

vif(step.CogLQ)
vif(step.CogAOS)
vif(step.CogBNT)
vif(step.Cogall)

sqrt(vif(step.CogLQ))
sqrt(vif(step.CogAOS))
sqrt(vif(step.CogBNT))
sqrt(vif(step.Cogall))
