install.packages("xlsx")
library(xlsx)
library(lm.beta)
rm(list = ls())

S3reg=read.csv(file.choose(),header=TRUE,as.is=TRUE)
attach(S3reg)
S3reg=read.xlsx(file.choose(),2,header=TRUE)
S3reg<-lm(S3reg$PMG~S3reg$F1+S3reg$F2+S3reg$F3+S3reg$F4+S3reg$AOS.DDK+S3reg$Aud.comp, data=S3reg)
summary(S3reg)
lm.beta(S3reg)

gvmodel<-gvlma(S3reg)
summary(gvmodel)
step.S3reg<-step(S3reg)
summary(step.S3reg)
lm.beta(step.S3reg)
vif(step.S3reg)
sqrt(vif(step.S3reg))

S3reg=read.xlsx(file.choose(),2,header=TRUE)
S3reg2<-lm(S3reg$PMGM~S3reg$F1+S3reg$F2+S3reg$F3+S3reg$F4+S3reg$AOS.DDK+S3reg$Aud.comp, data=S3reg)
summary(S3reg2)
gvmodel<-gvlma(S3reg2)
lm.beta(S3reg2)
summary(gvmodel)
lm.beta(step.S3reg2)
vif(step.S3reg2)
sqrt(vif(step.S3reg2))


outlierTest(S3reg)
qqPlot(S3reg, main="PMG outliers")
leveragePlots(S3reg)
avPlots(S3reg)
cutoff<-4/((nrow(S3reg)-length(S3reg$coefficients)-2))
plot(S3reg, which=4, cook.levels=cutoff)
influencePlot(S3reg, id.methods="identify", main="Influence Plot", sub="Circle size is proportional to Cook's Distance")
qqPlot(S3reg, main="QQ Plot")

sresid<-studres(S3reg)
hist(sresid, freq=FALSE, main="Distribution of Studentized Residuals")
xfit<-seq(min(sresid), max(sresid), length=40)
yfit<-dnorm(xfit)
lines(xfit, yfit)
ncvTest(S3reg)
spreadLevelPlot(S3reg)
vif(S3reg)
sqrt(vif(S3reg))
crPlots(S3reg)
residuals<-residuals(S3reg)
mean(S3reg$residuals)
acf(S3reg$residuals)
durbinWatsonTest(S3reg)
gvmodel<-gvlma(S3reg)
summary(gvmodel)

par(mfrow=c(2,2))
plot(S3reg3)