library(xlsx)
library (MASS)
library(coin)

#BEHAVIORAL TASKS 
##Accuracy
#all participants
ACCdata=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/05.12.18_Revision 2 Analyses/ACC.csv") 
wilcox.test(ACCdata$RJNN_Pre,ACCdata$RJNN_Post,paired=TRUE)
wilcox.test(ACCdata$RJNP_Pre ,ACCdata$RJNP_Post,paired=TRUE)
wilcox.test(ACCdata$SJNN_Pre,ACCdata$SJNN_Post,paired=TRUE)
wilcox.test(ACCdata$SJNP_Pre,ACCdata$SJNP_Post,paired=TRUE)
wilcox.test(ACCdata$PHNN_Pre,ACCdata$PHNN_Post,paired=TRUE)
wilcox.test(ACCdata$PHNP_Pre,ACCdata$PHNP_Post,paired=TRUE)
wilcox.test(ACCdata$CCJ_Pre,ACCdata$CCJ_Post,paired=TRUE)
wilcox.test(ACCdata$SCV_Pre,ACCdata$SCV_Post,paired=TRUE)
wilcox.test(ACCdata$SFV_Pre,ACCdata$SFV_Post,paired=TRUE)

wilcoxsign_test(ACCdata$RJNN_Pre ~ ACCdata$RJNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$RJNP_Pre ~ ACCdata$RJNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$SJNN_Pre ~ ACCdata$SJNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$SJNP_Pre ~ ACCdata$SJNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$PHNN_Pre ~ ACCdata$PHNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$PHNP_Pre ~ ACCdata$PHNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$CCJ_Pre ~ ACCdata$CCJ_Post,distribution="exact")
wilcoxsign_test(ACCdata$SCV_Pre ~ ACCdata$SCV_Post, distribution="exact")
wilcoxsign_test(ACCdata$SFV_Pre ~ ACCdata$SFV_Post,distribution="exact")
#responders
ACCdata=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/05.12.18_Revision 2 Analyses/ACC_R.csv") 
wilcox.test(ACCdata$RJNN_Pre,ACCdata$RJNN_Post,paired=TRUE)
wilcox.test(ACCdata$RJNP_Pre ,ACCdata$RJNP_Post,paired=TRUE)
wilcox.test(ACCdata$SJNN_Pre,ACCdata$SJNN_Post,paired=TRUE)
wilcox.test(ACCdata$SJNP_Pre,ACCdata$SJNP_Post,paired=TRUE)
wilcox.test(ACCdata$PHNN_Pre,ACCdata$PHNN_Post,paired=TRUE)
wilcox.test(ACCdata$PHNP_Pre,ACCdata$PHNP_Post,paired=TRUE)
wilcox.test(ACCdata$CCJ_Pre,ACCdata$CCJ_Post,paired=TRUE)
wilcox.test(ACCdata$SCV_Pre,ACCdata$SCV_Post,paired=TRUE)
wilcox.test(ACCdata$SFV_Pre,ACCdata$SFV_Post,paired=TRUE)

wilcoxsign_test(ACCdata$RJNN_Pre ~ ACCdata$RJNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$RJNP_Pre ~ ACCdata$RJNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$SJNN_Pre ~ ACCdata$SJNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$SJNP_Pre ~ ACCdata$SJNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$PHNN_Pre ~ ACCdata$PHNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$PHNP_Pre ~ ACCdata$PHNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$CCJ_Pre ~ ACCdata$CCJ_Post,distribution="exact")
wilcoxsign_test(ACCdata$SCV_Pre ~ ACCdata$SCV_Post, distribution="exact")
wilcoxsign_test(ACCdata$SFV_Pre ~ ACCdata$SFV_Post,distribution="exact")

#nonresponders 
ACCdata=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/05.12.18_Revision 2 Analyses/ACC_NR.csv") 
wilcox.test(ACCdata$RJNN_Pre,ACCdata$RJNN_Post,paired=TRUE)
wilcox.test(ACCdata$RJNP_Pre ,ACCdata$RJNP_Post,paired=TRUE)
wilcox.test(ACCdata$SJNN_Pre,ACCdata$SJNN_Post,paired=TRUE)
wilcox.test(ACCdata$SJNP_Pre,ACCdata$SJNP_Post,paired=TRUE)
wilcox.test(ACCdata$PHNN_Pre,ACCdata$PHNN_Post,paired=TRUE)
wilcox.test(ACCdata$PHNP_Pre,ACCdata$PHNP_Post,paired=TRUE)
wilcox.test(ACCdata$CCJ_Pre,ACCdata$CCJ_Post,paired=TRUE)
wilcox.test(ACCdata$SCV_Pre,ACCdata$SCV_Post,paired=TRUE)
wilcox.test(ACCdata$SFV_Pre,ACCdata$SFV_Post,paired=TRUE)

wilcoxsign_test(ACCdata$RJNN_Pre ~ ACCdata$RJNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$RJNP_Pre ~ ACCdata$RJNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$SJNN_Pre ~ ACCdata$SJNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$SJNP_Pre ~ ACCdata$SJNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$PHNN_Pre ~ ACCdata$PHNN_Post,distribution="exact")
wilcoxsign_test(ACCdata$PHNP_Pre ~ ACCdata$PHNP_Post,distribution="exact")
wilcoxsign_test(ACCdata$CCJ_Pre ~ ACCdata$CCJ_Post,distribution="exact")
wilcoxsign_test(ACCdata$SCV_Pre ~ ACCdata$SCV_Post, distribution="exact")
wilcoxsign_test(ACCdata$SFV_Pre ~ ACCdata$SFV_Post,distribution="exact")
##Reaction Time
#all participants

RTdata=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/05.12.18_Revision 2 Analyses/RT.csv") 
wilcox.test(RTdata$RJNN_Pre,RTdata$RJNN_Post,paired=TRUE)
wilcox.test(RTdata$RJNP_Pre,RTdata$RJNP_Post,paired=TRUE)
wilcox.test(RTdata$SJNN_Pre,RTdata$SJNN_Post,paired=TRUE)
wilcox.test(RTdata$SJNP_Pre,RTdata$SJNP_Post,paired=TRUE)
wilcox.test(RTdata$PVNN_Pre,RTdata$PVNN_Post,paired=TRUE)
wilcox.test(RTdata$PVNP_Pre,RTdata$PVNP_Post,paired=TRUE)
wilcox.test(RTdata$CCJ_Pre,RTdata$CCJ_Post,paired=TRUE)
wilcox.test(RTdata$SCV_Pre,RTdata$SCV_Post,paired=TRUE)
wilcox.test(RTdata$SFV_Pre,RTdata$SFV_Post,paired=TRUE)

wilcoxsign_test(RTdata$RJNN_Pre ~ RTdata$RJNN_Post,distribution="exact")
wilcoxsign_test(RTdata$RJNP_Pre ~ RTdata$RJNP_Post,distribution="exact")
wilcoxsign_test(RTdata$SJNN_Pre ~ RTdata$SJNN_Post,distribution="exact")
wilcoxsign_test(RTdata$SJNP_Pre ~ RTdata$SJNP_Post,distribution="exact")
wilcoxsign_test(RTdata$PVNN_Pre ~ RTdata$PVNN_Post,distribution="exact")
wilcoxsign_test(RTdata$PVNP_Pre ~ RTdata$PVNP_Post,distribution="exact")
wilcoxsign_test(RTdata$CCJ_Pre ~ RTdata$CCJ_Post,distribution="exact")
wilcoxsign_test(RTdata$SCV_Pre ~ RTdata$SCV_Post,distribution="exact")
wilcoxsign_test(RTdata$SFV_Pre ~ RTdata$SFV_Post,distribution="exact")

#responders
RTdata=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/05.12.18_Revision 2 Analyses/RT_R.csv") 
wilcox.test(RTdata$RJNN_Pre,RTdata$RJNN_Post,paired=TRUE)
wilcox.test(RTdata$RJNP_Pre ,RTdata$RJNP_Post,paired=TRUE)
wilcox.test(RTdata$SJNN_Pre,RTdata$SJNN_Post,paired=TRUE)
wilcox.test(RTdata$SJNP_Pre,RTdata$SJNP_Post,paired=TRUE)
wilcox.test(RTdata$PVNN_Pre,RTdata$PVNN_Post,paired=TRUE)
wilcox.test(RTdata$PVNP_Pre,RTdata$PVNP_Post,paired=TRUE)
wilcox.test(RTdata$CCJ_Pre,RTdata$CCJ_Post,paired=TRUE)
wilcox.test(RTdata$SCV_Pre,RTdata$SCV_Post,paired=TRUE)
wilcox.test(RTdata$SFV_Pre,RTdata$SFV_Post,paired=TRUE)

wilcoxsign_test(RTdata$RJNN_Pre ~ RTdata$RJNN_Post,distribution="exact")
wilcoxsign_test(RTdata$RJNP_Pre ~ RTdata$RJNP_Post,distribution="exact")
wilcoxsign_test(RTdata$SJNN_Pre ~ RTdata$SJNN_Post,distribution="exact")
wilcoxsign_test(RTdata$SJNP_Pre ~ RTdata$SJNP_Post,distribution="exact")
wilcoxsign_test(RTdata$PVNN_Pre ~ RTdata$PVNN_Post,distribution="exact")
wilcoxsign_test(RTdata$PVNP_Pre ~ RTdata$PVNP_Post,distribution="exact")
wilcoxsign_test(RTdata$CCJ_Pre ~ RTdata$CCJ_Post,distribution="exact")
wilcoxsign_test(RTdata$SCV_Pre ~ RTdata$SCV_Post, distribution="exact")
wilcoxsign_test(RTdata$SFV_Pre ~ RTdata$SFV_Post,distribution="exact")

#nonresponders 
RTdata=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/05.12.18_Revision 2 Analyses/RT_NR.csv") 
wilcox.test(RTdata$RJNN_Pre,RTdata$RJNN_Post,paired=TRUE)
wilcox.test(RTdata$RJNP_Pre ,RTdata$RJNP_Post,paired=TRUE)
wilcox.test(RTdata$SJNN_Pre,RTdata$SJNN_Post,paired=TRUE)
wilcox.test(RTdata$SJNP_Pre,RTdata$SJNP_Post,paired=TRUE)
wilcox.test(RTdata$PVNN_Pre,RTdata$PVNN_Post,paired=TRUE)
wilcox.test(RTdata$PVNP_Pre,RTdata$PVNP_Post,paired=TRUE)
wilcox.test(RTdata$CCJ_Pre,RTdata$CCJ_Post,paired=TRUE)
wilcox.test(RTdata$SCV_Pre,RTdata$SCV_Post,paired=TRUE)
wilcox.test(RTdata$SFV_Pre,RTdata$SFV_Post,paired=TRUE)

wilcoxsign_test(RTdata$RJNN_Pre ~ RTdata$RJNN_Post,distribution="exact")
wilcoxsign_test(RTdata$RJNP_Pre ~ RTdata$RJNP_Post,distribution="exact")
wilcoxsign_test(RTdata$SJNN_Pre ~ RTdata$SJNN_Post,distribution="exact")
wilcoxsign_test(RTdata$SJNP_Pre ~ RTdata$SJNP_Post,distribution="exact")
wilcoxsign_test(RTdata$PVNN_Pre ~ RTdata$PVNN_Post,distribution="exact")
wilcoxsign_test(RTdata$PVNP_Pre ~ RTdata$PVNP_Post,distribution="exact")
wilcoxsign_test(RTdata$CCJ_Pre ~ RTdata$CCJ_Post,distribution="exact")
wilcoxsign_test(RTdata$SCV_Pre ~ RTdata$SCV_Post, distribution="exact")
wilcoxsign_test(RTdata$SFV_Pre ~ ACCdata$SFV_Post,distribution="exact")

# STANDARDIZED TESTS 

library(coin)

#all participants
STdata=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/03.13.18_Revision Analyses/03.13.18_Raw data for treatment patients/St_Tx.csv") 
wilcoxsign_test(STdata$LQ_Pre ~ STdata$LQ_Post,distribution="exact")
wilcoxsign_test(STdata$CQ_Pre ~ STdata$CQ_Post,distribution="exact")
wilcoxsign_test(STdata$AQ_Pre ~ STdata$AQ_Post,distribution="exact") 
wilcoxsign_test(STdata$CLQT_CompSev_Pre ~ STdata$CLQT_CompSev_Post,distribution="exact")
wilcoxsign_test(STdata$BNT_Pre ~ STdata$BNT_Post,distribution="exact")
wilcoxsign_test(STdata$PAPT_Pre ~ STdata$PAPT_Post,distribution="exact")
wilcoxsign_test(STdata$PALPA_1_Pre ~ STdata$PALPA_1_Post,distribution="exact")
wilcoxsign_test(STdata$PALPA_51_Pre ~ STdata$PALPA_51_Post,distribution="exact")
wilcoxsign_test(STdata$NNB_CN_Pre ~ STdata$NNB_CN_Post,distribution="exact")


wilcox.test(STdata$LQ_Pre,STdata$LQ_Post,paired=TRUE)
wilcox.test(STdata$CQ_Pre,STdata$CQ_Post,paired=TRUE)
wilcox.test(STdata$AQ_Pre,STdata$AQ_Post,paired=TRUE)
wilcox.test(STdata$CLQT_CompSev_Pre,STdata$CLQT_CompSev_Post,paired=TRUE)
wilcox.test(STdata$BNT_Pre,STdata$BNT_Post,paired=TRUE)
wilcox.test(STdata$PAPT_Pre,STdata$PAPT_Post,paired=TRUE)
wilcox.test(STdata$PALPA_1_Pre,STdata$PALPA_1_Post,paired=TRUE)
wilcox.test(STdata$PALPA_51_Pre,STdata$PALPA_51_Post,paired=TRUE)
wilcox.test(STdata$NNB_CN_Pre,STdata$NNB_CN_Post,paired=TRUE)


#Responders
STdataR=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/03.13.18_Revision Analyses/03.13.18_Raw data for treatment patients/ST_R.csv")
wilcoxsign_test(STdataR$LQ_Pre ~ STdataR$LQ_Post,distribution="exact")
wilcoxsign_test(STdataR$CQ_Pre ~ STdataR$CQ_Post,distribution="exact")
wilcoxsign_test(STdataR$AQ_Pre ~ STdataR$AQ_Post,distribution="exact") 
wilcoxsign_test(STdataR$CLQT_CompSev_Pre ~ STdataR$CLQT_CompSev_Post,distribution="exact")
wilcoxsign_test(STdataR$BNT_Pre ~ STdataR$BNT_Post,distribution="exact")
wilcoxsign_test(STdataR$PAPT_Pre ~ STdataR$PAPT_Post,distribution="exact")
wilcoxsign_test(STdataR$PALPA_1_Pre ~ STdataR$PALPA_1_Post,distribution="exact")
wilcoxsign_test(STdataR$PALPA_51_Pre ~ STdataR$PALPA_51_Post,distribution="exact")
wilcoxsign_test(STdataR$NNB_CN_Pre ~ STdataR$NNB_CN_Post,distribution="exact")


wilcox.test(STdataR$LQ_Pre,STdataR$LQ_Post,paired=TRUE)
wilcox.test(STdataR$CQ_Pre,STdataR$CQ_Post,paired=TRUE)
wilcox.test(STdataR$AQ_Pre,STdataR$AQ_Post,paired=TRUE)
wilcox.test(STdataR$CLQT_Pre,STdataR$CLQT_Post,paired=TRUE)
wilcox.test(STdataR$BNT_Pre,STdataR$BNT_Post,paired=TRUE)
wilcox.test(STdataR$PAPT_Pre,STdataR$PAPT_Post,paired=TRUE)
wilcox.test(STdataR$PALPA_1_Pre,STdataR$PALPA_1_Post,paired=TRUE)
wilcox.test(STdataR$PALPA_51_Pre,STdataR$PALPA_51_Post,paired=TRUE)
wilcox.test(STdataR$NNB_CN_Pre,STdataR$NNB_CN_Post,paired=TRUE)

#Non-Responders
STdataNR=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/03.13.18_Revision Analyses/03.13.18_Raw data for treatment patients/St_NR.csv")
wilcoxsign_test(STdataNR$LQ_Pre ~ STdataNR$LQ_Post,distribution="exact")
wilcoxsign_test(STdataNR$CQ_Pre ~ STdataNR$CQ_Post,distribution="exact")
wilcoxsign_test(STdataNR$AQ_Pre ~ STdataNR$AQ_Post,distribution="exact") 
wilcoxsign_test(STdataNR$CLQT_Pre ~ STdataNR$CLQT_Post,distribution="exact")
wilcoxsign_test(STdataNR$BNT_Pre ~ STdataNR$BNT_Post,distribution="exact")
wilcoxsign_test(STdataNR$PAPT_Pre ~ STdataNR$PAPT_Post,distribution="exact")
wilcoxsign_test(STdataNR$PALPA_1_Pre ~ STdataNR$PALPA_1_Post,distribution="exact")
wilcoxsign_test(STdataNR$PALPA_51_Pre ~ STdataNR$PALPA_51_Post,distribution="exact")
wilcoxsign_test(STdataNR$NNB_CN_Pre ~ STdataNR$NNB_CN_Post,distribution="exact")


wilcox.test(STdataNR$LQ_Pre,STdataNR$LQ_Post,paired=TRUE)
wilcox.test(STdataNR$CQ_Pre,STdataNR$CQ_Post,paired=TRUE)
wilcox.test(STdataNR$AQ_Pre,STdataNR$AQ_Post,paired=TRUE)
wilcox.test(STdataNR$CLQT_CompSev_Pre,STdataNR$CLQT_CompSev_Post,paired=TRUE)
wilcox.test(STdataNR$BNT_Pre,STdataNR$BNT_Post,paired=TRUE)
wilcox.test(STdataNR$PAPT_Pre,STdataNR$PAPT_Post,paired=TRUE)
wilcox.test(STdataNR$PALPA_1_Pre,STdataNR$PALPA_1_Post,paired=TRUE)
wilcox.test(STdataNR$PALPA_51_Pre,STdataNR$PALPA_51_Post,paired=TRUE)
wilcox.test(STdataNR$NNB_CN_Pre,STdataNR$NNB_CN_Post,paired=TRUE)


BL=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/03.13.18_Revision Analyses/Baseline_RvNR.csv")
wilcox.test(BL$AQ_R,BL$AQ_NR,paired=TRUE)
wilcoxsign_test(BL$AQ_R~BL$AQ_NR,distribution="exact")
wilcox.test(BL$CLQT_R,BL$CLQT_NR,paired=TRUE)
wilcoxsign_test(BL$CLQT_R~BL$CLQT_NR,distribution="exact")
