library(tidyverse)
install.packages("coin")
library(coin)
library(car)
Demo_use=read.csv("R:/KiranLab4/P50 Neurobiology of Recovery of Aphasia/Tx, Gen, Transfer Analyses - Natalie/05.12.18_Revision 2 Analyses/Demo_use.csv")
qqPlot(Demo_use$Tx_Age, main="Age")
hist(Demo_use$Tx_Age, main="Age")
qqPlot(Demo_use$Tx_MPO, main="MPO")
hist(Demo_use$Tx_MPO, main="MPO")
qqPlot(Demo_use$Tx_WAB_AQ, main="AQ")
hist(Demo_use$Tx_WAB_AQ, main="AQ")
qqPlot(Demo_use$Tx_CLQT_CS, main="CLQT")
hist(Demo_use$Tx_CLQT_CS, main="CLQT")
qqPlot(Demo_use$Tx_BLnam, main="BL nam")
hist(Demo_use$Tx_BLnam, main="BL nam")


wilcox.test(Demo_use$Tx_Age, Demo_use$NHx_Age,paired=TRUE)
wilcoxsign_test(Demo_use$Tx_Age~Demo_use$NHx_Age,distribution="exact")
wilcox.test(Demo_use$Tx_MPO, Demo_use$NHx_MPO,paired=TRUE)
wilcoxsign_test(Demo_use$Tx_MPO~Demo_use$NHx_MPO,distribution="exact")
wilcox.test(Demo_use$Tx_WAB_AQ, Demo_use$NHX_WAB_AQ,paired=TRUE)
wilcoxsign_test(Demo_use$Tx_WAB_AQ~Demo_use$NHX_WAB_AQ,distribution="exact")
wilcox.test(Demo_use$Tx_CLQT_CS, Demo_use$NHx_CLQT_CS,paired=TRUE)
wilcoxsign_test(Demo_use$Tx_CLQT_CS~Demo_use$NHx_CLQT_CS,distribution="exact")
wilcox.test(Demo_use$Tx_BLnam, Demo_use$NHx_BLnam,paired=TRUE)
wilcoxsign_test(Demo_use$Tx_BLnam~Demo_use$NHx_BLnam,distribution="exact")

